Added a strategy for multipliers
anbclausen/pokelin pull request #7
Opened 2020-11-02 22:51 UTC by frederik1904

Features:
Multiplier strategy, and an implementation that gives the original multiplier values
All the original types
An object for positions

All of it should be tested :)

2020-11-02 23:25 UTC, anbclausen requested changes
Also: 
1) OriginalMultiplierStrategy is really nice. Where did you get all the data?
2) We're currently discussing whether to use standard JUnit or Hamcrest. We'll let you know. :)

2020-11-02 23:25 UTC, anbclausen commented on src/main/kotlin/framework/Position.kt
> +    override fun equals(other: Any?): Boolean {
You should auto generate equals methods to ensure correctness. Also use bail out fast when possible.
Here's what I got from IntelliJ:
```
override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Position

        if (row != other.row) return false
        if (col != other.col) return false

        return true
    }
```

2020-11-02 23:25 UTC, anbclausen commented on src/main/kotlin/framework/Position.kt
> +        return String.format("[$row,$col]")
String.format is redundant. "[$row, $col]" works directly in Kotlin.

2020-11-02 23:25 UTC, anbclausen commented on src/main/kotlin/framework/Position.kt
> +    override fun equals(other: Any?): Boolean {
This also means you do not have to develop the equals methods using TDD.

2020-11-02 23:25 UTC, anbclausen commented on src/main/kotlin/framework/Types.kt
> +}
Consider moving these enums in GameConstants or give file another name implicating the responsibilities of the file. "Types" suggests that it only holds types.

2020-11-03 08:49 UTC, frederik1904 commented
>     1. OriginalMultiplierStrategy is really nice. Where did you get all the data?
The data comes from this diagram: https://2.bp.blogspot.com/-H4BnLpEKS94/VF62mw1fm4I/AAAAAAAAAAk/oezpFub4UCw/s1600/types.jpg 😄

2020-11-03 09:10 UTC, anbclausen requested changes
Much better. I'll approve after fixing these two things :)

2020-11-03 09:10 UTC, anbclausen commented on src/main/kotlin/framework/GameConstants.kt
> +    Inefective(0.0), Weak(0.5), Normal(1.0), Strong(2.0);
Typo. Should be Ineffective.

2020-11-03 09:10 UTC, anbclausen commented on src/test/kotlin/OriginalMultiplierStrategyTest.kt
> +import junit.framework.Assert.assertTrue
We have settled on using Hamcrest. Can you please refactor these tests.

We're using 
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

2020-11-03 10:18 UTC, anbclausen approved these changes
Looks good to me :)

2020-11-03 10:25 UTC, frederik1904 commented
@anbclausen mangler der ikke docs ?

2020-11-03 10:27 UTC, soer7022 requested changes

2020-11-03 10:27 UTC, soer7022 commented on src/main/kotlin/framework/GameConstants.kt
> +enum class Types(val type: String) {
Needs JavaDoc

2020-11-03 10:27 UTC, soer7022 commented on src/main/kotlin/framework/GameConstants.kt
> +enum class EffectLevel(val multiplier: Double) {
Needs JavaDoc

2020-11-03 10:27 UTC, soer7022 commented on src/main/kotlin/framework/Position.kt
> +class Position(var row: Int, var col: Int) {
Needs JavaDoc

2020-11-03 10:27 UTC, soer7022 commented on src/main/kotlin/framework/strategy/MultiplierStrategy.kt
> +interface MultiplierStrategy {
Needs JavaDoc

2020-11-03 10:27 UTC, soer7022 commented on src/main/kotlin/standard/OriginalMultiplierStrategy.kt
> +    private val effectivenessMap = mapOf(
This REALLY Needs JavaDoc

2020-11-03 10:55 UTC, soer7022 approved these changes
Looks good to me

2020-11-03 12:27 UTC, dangerstone requested changes

2020-11-03 12:27 UTC, dangerstone commented on src/main/kotlin/standard/OriginalMultiplierStrategy.kt
> +    private val effectivenessMap = mapOf(
neat! :D

2020-11-03 12:27 UTC, dangerstone commented on src/main/kotlin/framework/Position.kt
> +        if (other == null
Refactor to bail out fast

2020-11-03 14:08 UTC, frederik1904 commented
@dangerstone tror du er kommet til at kigge på noget gammelt kode 😄

2020-11-03 14:22 UTC, dangerstone approved these changes

2020-11-03 14:27 UTC, merged