Updated issue templates
anbclausen/pokelin pull request #9
Opened 2020-11-02 23:50 UTC by anbclausen

Makes it easier to create issues.

2020-11-03 08:43 UTC, soer7022 requested changes

2020-11-03 08:43 UTC, soer7022 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
I think that assignees should be handled by GitHub, so we don't have to manually update this.

2020-11-03 08:43 UTC, soer7022 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
Labels as well

2020-11-03 09:21 UTC, anbclausen commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
From what I can see I can only assign specific people by default. This doesn't make sense, as then I, for example, would be assigned to everything per deafult. Am I misunderstanding something here?

I put 'enchancement' as default label. If you have any ideas for making this template better, please do. I have never created a template like this before. :D

2020-11-03 10:32 UTC, soer7022 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
I think that it will start out as being unassigned and then we can assign it to a single person when we decide who should implement the feature 😄

2020-11-03 14:23 UTC, anbclausen commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
Do I just put "unassigned"?

2020-11-03 14:26 UTC, soer7022 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
I think we remove the field from the md file and then just use the built in function in GitHub

2020-11-03 14:28 UTC, anbclausen commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
Done.

2020-11-03 18:13 UTC, soer7022 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
Can you do it for labels as well?

2020-11-03 19:37 UTC, anbclausen commented on .github/ISSUE_TEMPLATE/feature_request.md
> +assignees: ''
You're a hard man to please.

2020-11-03 20:43 UTC, soer7022 approved these changes

2020-11-04 18:06 UTC, anbclausen commented
Stinna approved IRL. Merging. :)

2020-11-04 18:06 UTC, merged